config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :microposts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 }, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "Hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost successfully created' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
    @microposts = Micropost.all
  end

  private

  def set_micropost
    @micropost = Micropost.find(params[:id])
  end

  def micropost_params
    params.require(:micropost).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
    @users = User.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_micropost_form.html.erb
<%= form_with(model: micropost, local: true) do |micropost_form| %>

  <div class="field">
    <%= micropost_form.label :content %>
    <%= micropost_form.text_field :content %>
  </div>

  <div class="field">
    <%= micropost_form.label :user_id %>
    <%= micropost_form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= micropost_form.submit %>
  </div>
<% end %>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/microposts/edit.html.erb
<h1>Microposts#edit</h1>
<p>Find me in app/views/microposts/edit.html.erb</p>

app/views/microposts/index.html.erb
<h1>Microposts#index</h1>
<p>Find me in app/views/microposts/index.html.erb</p>

<%= @microposts.each do |micropost| %>
  <p><%= micropost.content %></p>
  <p><%= micropost.user_id %></p>
<% end %>

app/views/microposts/new.html.erb
<h1>Microposts#new</h1>
<p>Find me in app/views/microposts/new.html.erb</p>

<p id="notice"> <%= notice %></p>

<%= render 'micropost_form', micropost: @micropost %>

app/views/microposts/show.html.erb
<h1>Microposts#show</h1>
<p>Find me in app/views/microposts/show.html.erb</p>

<p id="notice"><%= notice %></p>

<div>
  <h2>Content: </h2>
  <%= @micropost.content %>
</div>

<div>
  <h2>User id: </h2>
  <%= @micropost.user_id %>
</div>

app/views/microposts/update.html.erb
<h1>Microposts#update</h1>
<p>Find me in app/views/microposts/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<p id="notice"> <%= notice %> </p>
<% @users.each do |user| %>
  <p><%= user.name %></p>
  <p><%= user.email %></p>
<% end %>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Show posts', microposts_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <h2>Name: </h2>
  <%= @user.name %>
</div>

<div>
  <h2>Email: </h2>
  <%= @user.email %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>